title: C++ course
description: This is a C++ course from basic to advanced
template:
  repo: c++-course-template
  name: c++-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
